dependencies:
  - name: nginx-ingress
    version: 1.28.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: ingressEnabled
  - name: rabbitmq
    version: 7.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: ingestion.enabled
  - name: solr
    version: 1.5.2
    repository: http://storage.googleapis.com/kubernetes-charts-incubator

  

