dependencies:
  - name: nginx-ingress
    version: 1.28.2
    repository: https://charts.helm.sh/stable
    condition: nginx-ingress.enabled
  - name: rabbitmq
    version: 8.24.13
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: rabbitmq.enabled
  - name: solr
    version: 2.1.7
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: solr.enabled
  - name: cassandra
    version: 5.5.3
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: cassandra.enabled

