apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitbasedconfigs.sdap.apache.org
spec:
  group: sdap.apache.org
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: gitbasedconfigs
    singular: gitbasedconfig
    kind: GitBasedConfig
    shortNames:
      - gitcfg
  validation:
    openAPIV3Schema:
      type: object
      properties:
        git-url:
          type: string
        git-branch:
          type: string
        git-token:
          type: string
        update-every-seconds:
          type: int
        local-dir:
          type: string
        config-map:
          type: string

